### ISSUE TITLE
Case Study

### ISSUE THREAD

**Issue by rcodydukew** [asu-cis440-summer/studiocracy-analytics-hjwwy#14]
Netflix

**Comment by cwarhola** [comment]
S3 - http://aws.amazon.com/s3/
Elastic Block Store (EBS) - http://aws.amazon.com/ebs/
CloudFront - http://aws.amazon.com/cloudfront/
Glacier - http://aws.amazon.com/glacier/
Storage Gateway - http://aws.amazon.com/storagegateway/
Import/Export- http://aws.amazon.com/importexport/
