### ISSUE TITLE
AWS-Cross Service

### ISSUE THREAD

**Issue by rcodydukew** [asu-cis440-summer/studiocracy-analytics-hjwwy#15]
support
marketplace
management console
sdks, ide kits and clis

**Comment by cwarhola** [comment]
Support - https://aws.amazon.com/premiumsupport/
Marketplace - https://aws.amazon.com/marketplace/help/200777860/ref=help_ln_sibling/186-8470972-3446729#topic1
Management Console - http://aws.amazon.com/console/
SDKs, IDE Kits, Command Line Tools - http://aws.amazon.com/tools/
