### ISSUE TITLE
Familiarize with Ruby on Rails

### ISSUE THREAD

**Issue by rcodydukew** [asu-cis440-summer/studiocracy-analytics-hjwwy#46]
http://www.theodinproject.com/ruby-on-rails

**Comment by msopha-phd** [comment]
Here are a few others, courtesy of Jordan Parra:

https://drive.google.com/file/d/0B8dyTUAKdOOyUWV6WkNaOG5NSnM/view
https://www.railstutorial.org/book
http://www.codelearn.org/

**Comment by yumsdd** [comment]
en, Thanks sopha, It would be helpful.
