### ISSUE TITLE
Create a D3 visualization for the dashboard

### ISSUE THREAD

**Issue by acjohn25** [asu-cis440-summer/studiocracy-analytics-hjwwy#66]

**Comment by cwarhola** [comment]
Had a couple of thoughts on how to track site population by demographics. While using cookies or perhaps something simpler such as manual user entry, the site couple upload Location data to one of these charts. I found the best two options would either be:

Cartogram -
http://bl.ocks.org/mbostock/4055908

Choropleth - 
http://bl.ocks.org/mbostock/4060606

Thoughts?
